apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-1
  project: default
  source:
    path: charts/custom-chart
    repoURL: https://github.com/hutcho66/argotest.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: 1.22.0
        env_vars:
          - name: MY_ENV_VAR
            value: my_env_value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
