apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/argoproj-labs/argocd-image-updater.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
